{'char': 'm',
 'left': {'char': 'e',
          'left': None,
          'right': None,
          'mid': {'char': 'r',
                  'left': None,
                  'right': None,
                  'mid': {'char': 'i',
                          'left': None,
                          'right': None,
                          'mid': {'char': 'c',
                                  'left': None,
                                  'right': None,
                                  'mid': {'char': 'a',
                                          'left': None,
                                          'right': None,
                                          'mid': {'char': 'h',
                                                  'left': None,
                                                  'right': None,
                                                  'mid': None,
                                                  'is_end': True},
                                          'is_end': False},
                                  'is_end': False},
                          'is_end': False},
                  'is_end': False},
          'is_end': False},
 'right': None,
 'mid': {'char': 'i',
         'left': None,
         'right': None,
         'mid': {'char': 'k',
                 'left': None,
                 'right': None,
                 'mid': {'char': 'e',
                         'left': None,
                         'right': None,
                         'mid': None,
                         'is_end': True},
                 'is_end': False},
         'is_end': False},
 'is_end': False}
